- DEFINE_MODELS
- id: project.models.Passenger
  fields:
  - name: testthing
    type: string
  - [name, string]
  - [email, string]
  methods:
  - name: toCSV
    args: []
    return: string
    gencode: |
      (return (iget name))
- id: project.models.Booking
  fields:
  - name: passenger
    type: project.models.Passenger
  - name: notes
    type: string
