- DEFINE_MODELS
- id: project.models.Passenger
  fields:
  - name: age
    type: int
  - name: name
    type: string
  #- [name, string]
  - [email, string]
  methods:
  - name: toCSV
    args: []
    return: string
    gencode: |
      (return (icall getName ()))
  - name: getDiscountPercent
    args: []
    return: int
    gencode: |
      (vset age (icall getAge ()))
      (if (< (vget age) (int 12)) (
        (return (int 100))
      ))
      (if (< (vget age) (int 18)) (
        (return (int 20))
      ))
      (if (< (vget age) (int 24)) (
        (return (int 10))
      ))
      (if (< (int 65) (vget age)) (
        (return (int 50))
      ))
- id: project.models.Booking
  fields:
  - name: passenger
    type: project.models.Passenger
  - name: notes
    type: string
